### PR TITLE
customize version and source URL

### PR DESCRIPTION
**Pull request by Joshix-1**
(to make these changes work, I think you need to rebuild the front-end)

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
Would really love to see this land, had to ask Renaud for a link to this repository since I couldn't discover it easily from your site

**Comment by Joshix-1** [comment]
I've rebased the pr

**Comment by thomas-pike** [comment]
Ah, sorry, I hadn't seen this PR until now. Thanks, I'll take a look at it.

**Comment by thomas-pike** [comment]
This has been cherry-picked to our latest branch and deployed in production. Thank you!

**Pull request closed without merging**
